FROM oven/bun:alpine

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json    
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./.npmrc ./.npmrc
COPY ./apps/webhook-callback ./apps/webhook-callback

RUN bun install

EXPOSE 8080

CMD ["bun", "run", "start:webhook"]